version: "3.9"  # optional since v1.27.0
services:
  nest:
    container_name: nest
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql

  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=medicos
      - MYSQL_ROOT_PASSWORD=rootpass


